
# This file is part of the dinStaticPlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# dinStaticPlugin cache routing configuration
#
# @package     dinStaticPlugin
# @subpackage  config
# @author      Nicolay N. Zyk <relo.san@gmail.com>
routes:
    static_categories:
        type:           'custom'
        get:
            model:      'DinStaticCategory'
            method:     'getCategoriesQuery'
            path:       ':_root/static_categories'
            key:        ':_i18n'
        remove:
            default:
                path:   ':_root/static_categories'
                key:    '*'

links:
    DinStaticCategory:  ['static_categories']

#EOF