
# This file is part of the dinStaticPlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# dinStaticPlugin routing configuration
#
# @package     dinStaticPlugin
# @subpackage  config
# @author      Nicolay N. Zyk <relo.san@gmail.com>

din_static_page_admin:
    class:                      'sfDoctrineRouteCollection'
    options:
        model:                  'DinStaticPage'
        module:                 'dinStaticPageAdmin'
        prefix_path:            '/adm/static/:category_id/pages'
        column:                 'id'
        with_wildcard_routes:   true

din_static_category_admin:
    class:                      'sfDoctrineRouteCollection'
    options:
        model:                  'DinStaticCategory'
        module:                 'dinStaticCategoryAdmin'
        prefix_path:            '/adm/static'
        column:                 'id'
        with_wildcard_routes:   true

#EOF